---
apiVersion: v1
kind: ReplicationController
metadata:
  name: angularfrontend-rc
  namespace: easytravel
spec:
  replicas: 1
  selector:
    app: angularfrontend
  template: 
    metadata:
      labels:
        app: angularfrontend
        tier: frontend
    spec:
      containers:
      - name: angularfrontend
        image: dynatrace/easytravel-angular-frontend:2.0.0.3322
        env:
        - name: ET_BACKEND_URL
          value: http://easytravel-backend:8080
        ports:
        - containerPort: 8080
        - containerPort: 8280
