apiVersion: v1
kind: Service
metadata:
  labels:
    app: easytravel-angularfrontend
  name: easytravel-angularfrontend
  namespace: easytravel
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    app: easytravel-angularfrontend
  type: LoadBalancer